# Generated by Django 5.1.8 on 2025-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cognom1', models.CharField(max_length=50)),
                ('cognom2', models.CharField(blank=True, max_length=50, null=True)),
                ('correu', models.EmailField(max_length=254)),
                ('curs', models.CharField(max_length=100)),
                ('moduls', models.TextField()),
                ('rol', models.CharField(choices=[('teacher', 'Professor/a'), ('student', 'Alumne/a')], max_length=7)),
                ('tutor', models.BooleanField(default=False)),
            ],
        ),
    ]
