# Generated by Django 5.1.8 on 2025-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Persones'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='cognom1',
            field=models.CharField(max_length=50, verbose_name='Primer Cognom'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cognom2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segon Cognom'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correu',
            field=models.EmailField(max_length=254, verbose_name='Correu electrònic'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='curs',
            field=models.CharField(max_length=100, verbose_name='Curs'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='moduls',
            field=models.TextField(verbose_name='Mòduls'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('teacher', 'Professor/a'), ('student', 'Alumne/a')], max_length=7, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tutor',
            field=models.BooleanField(default=False, verbose_name='Tutor'),
        ),
    ]
