version: '3.1'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: itic_db
      POSTGRES_USER: itic_user
      POSTGRES_PASSWORD: itic
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 2024_luis.montiel@itic.cat
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgadmin-data:
